on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml

  check-conventional-commits:
    uses: armakuni/github-actions/.github/workflows/check-conventional-commits.yml@v0.10.0

  create-release:
    needs:
      - run-tests
      - check-conventional-commits
    if: github.ref == 'refs/heads/main'
    uses: armakuni/github-actions/.github/workflows/tag-and-release.yml@v0.10.0
    secrets: inherit

  dependabot-merge:
    if: ${{ github.actor == 'dependabot[bot]' && github.ref != 'refs/heads/main' && github.event_name == 'pull_request' }}
    needs:
      - run-tests
      - check-conventional-commits
    uses: armakuni/github-actions/.github/workflows/dependabot-automerge.yml@v0.10.0
    with:
      merge-strategy: rebase