on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml

  check-conventional-commits:
    uses: armakuni/github-actions/.github/workflows/check-conventional-commits.yml@v0.4.1

  all-tests-succeeded:
    needs:
      - run-tests
      - check-conventional-commits
    runs-on: ubuntu-latest
    steps:
      - run: echo OK

  create-release:
    needs:
      - all-tests-succeeded
    if: github.ref == 'refs/heads/main'
    uses: armakuni/github-actions/.github/workflows/tag-and-release.yml@v0.4.1
    secrets: inherit