on:
  workflow_call:

env:
  go-version: '^1.21.1'

jobs:
  go-fmt:
    name: run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}
      - name: gofmt
        run: gofmt -s -l .

  go-test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}
      - name: go test
        run: go test ./...
